device:
    gpu: 2
    n_workers: 0


models_name:
    - bisenetX39
    #- bisenetR18
    - bisenetR101 
    #- ddrnet23
    - ddrnet23Slim
    - icnet
    - pspnet
    - segformer_bo
    - segformer_b1
    #- segformer_b5
    - deeplabv3_mobilenet
    - deeplabv3_resnet
    #- pidnet_s
    - pidnet_m
    #- pidnet_l
   

test_name: 'test_attack_1_ablation'


attack_configurations:

  - name: "200_200_eps16_iter200_rep3_leftcorner"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 3
      attack_position: 'left_corner'

  - name: "200_200_eps16_iter200_rep1_leftcorner"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 1
      attack_position: 'left_corner'
      
  - name: "200_200_eps16_iter200_rep1_center"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 1
      attack_position: 'center'

  - name: "200_200_eps16_iter200_rep2_center"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 2
      attack_position: 'center'

  - name: "200_200_eps16_iter200_rep3_center"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 3
      attack_position: 'center'

  - name: "200_200_eps16_iter200_rep4_center"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 4
      attack_position: 'center'

  - name: "200_200_eps16_iter200_rep5_center"
    settings:
      patch_size: [200,200] 
      epsilon: 0.062745 #16/255
      alpha: 0.0156865 #4/255
      num_steps: 50
      max_iterations: 5
      attack_position: 'center'
